apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: debugcontainerprobe
spec:
  replicas: 2
  template:
    metadata:
      labels:
        service: site
        app: debugcontainerprobe
    spec:
      containers:
      - name: debugcontainer
        image: danielmeixner/debugcontainer
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /ping
            port: 80
          periodSeconds: 10
          timeoutSeconds: 10


---

apiVersion: v1
kind: Service
metadata:
  name: debugcontainerprobe
spec:
  selector:
    app: debugcontainerprobe
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: debugcontainerprobe
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: debugcontainerprobe
          servicePort: 80
