apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ping-ingress-prefix
  namespace: default
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/backend-path-prefix: "/ping"
spec:
  rules:
  - http:
      paths:
      - path: /pong
        backend:
          serviceName: debugcontainerprobe
          servicePort: 80
