apiVersion: v1
kind: Service
metadata:
  name: svca
  labels:
    name: svca    
spec:
  selector:
    name: appa
  type: LoadBalancer
  ports:
   - port: 80
     name: http
     targetPort: 80
     protocol: TCP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: appa
spec:
  replicas: 1
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        name: appa
        app: dbg
    spec:
      containers:
      - name: appa
        image: danielmeixner/debugcontainer:latest
        ports:
          - containerPort: 80
            name: http         
            protocol: TCP
        env: 
          - name: "SERVICEENDPOINTHOST"
            value: "svcb"
          - name: "SERVICEENDPOINTPATH"
            value: "/api/cascade"              
          - name: "COLOR"
            value: "red"
          - name: "SERVICEENDPOINTPORT"
            value: "80"

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: red-rgv2cw-ing
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/waf-policy-for-path: "subscriptions/7f28d486-9ef2-4bd9-a295-e66f5949c6b2/resourceGroups/MC_aksagw_aksagw_westeurope/providers/Microsoft.Network/applicationGatewayWebApplicationFirewallPolicies/dmxpolicy"
spec:
  rules:
  - host: red.rgv2cw.org
    http:
      paths:
      - path: /
        backend:
          serviceName: svca
          servicePort: 80
