---
apiVersion: v1
kind: Service
metadata:
  name: svcb
  labels:
    name: svcb
spec:
  selector:
    name: appb
  type: LoadBalancer
  ports:
   - port: 80
     name: http
     targetPort: 80
     protocol: TCP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: appb
spec:
  replicas: 2
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        name: appb
        app: dbg
    spec:
      terminationGracePeriodSeconds: 101
      containers:
      - name: appb
        image: danielmeixner/debugcontainer:latest
        ports:
          - containerPort: 80
            name: http         
            protocol: TCP
        env: 
          - name: "SERVICEENDPOINTHOST"
            value: "svcc"
          - name: "SERVICEENDPOINTPATH"
            value: "/api/whoareu"              
          - name: "COLOR"
            value: "green"
          - name: "SERVICEENDPOINTPORT"
            value: "80"
        lifecycle:
          preStop:
            exec:
              command: ["sleep","90"]
        livenessProbe:
          httpGet:
            path: /
            port: 80
          periodSeconds: 4
          timeoutSeconds: 5
          failureThreshold: 3

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: color-rgv2cw-ing
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/connection-draining: "true"
    appgw.ingress.kubernetes.io/connection-draining-timeout: "30"
spec:
  rules:
  - host: color.rgv2cw.org
    http:
      paths:
      - path: /
        backend:
          serviceName: svcb
          servicePort: 80
---
